Repository canoo/dolphin-platform, pull requests merged in 2018-02, with the labels that each got.

#838 Remote Validation
  platform-extras/dolphin-platform-bean-validation-rest/dolphin-platform-bean-validation-rest.gradle
  platform-extras/dolphin-platform-bean-validation-rest/src/main/java/com/canoo/dp/impl/validation/rest/InvalidJsonException.java
  platform-extras/dolphin-platform-bean-validation-rest/src/main/java/com/canoo/dp/impl/validation/rest/RemoteConstants.java
  platform-extras/dolphin-platform-bean-validation-rest/src/main/java/com/canoo/dp/impl/validation/rest/validator/RemoteValidationConfiguration.java
  platform-extras/dolphin-platform-bean-validation-rest/src/main/java/com/canoo/dp/impl/validation/rest/validator/RemoteValidationServlet.java
  platform-extras/dolphin-platform-bean-validation-rest/src/main/java/com/canoo/dp/impl/validation/rest/validator/impl/ConstraintsViolationSerializer.java
  platform-extras/dolphin-platform-bean-validation-rest/src/main/java/com/canoo/dp/impl/validation/rest/validator/impl/DefaultValidationConfiguration.java
  platform-extras/dolphin-platform-bean-validation-rest/src/main/java/com/canoo/dp/impl/validation/rest/validator/impl/RemoteValidator.java
  platform/dolphin-platform-core/src/main/java/com/canoo/dp/impl/platform/core/PlatformVersion.java
  platform/dolphin-platform-core/src/main/java/com/canoo/dp/impl/platform/core/ansi/PlatformLogo.java
  settings.gradle
Labels: in progress

#835 2 small extra modules that helps to handle data (like JPA)
  platform-extras/dolphin-platform-data-audit/dolphin-platform-data-audit.gradle
  platform-extras/dolphin-platform-data-audit/src/main/java/com/canoo/dp/impl/platform/data/audit/AuditContext.java
  platform-extras/dolphin-platform-data-audit/src/main/java/com/canoo/dp/impl/platform/data/audit/Auditable.java
  platform-extras/dolphin-platform-data-jpa/dolphin-platform-data-jpa.gradle
  platform-extras/dolphin-platform-data-jpa/src/main/java/com/canoo/dp/impl/platform/data/jpa/AbstractEntity.java
  platform-extras/dolphin-platform-data-jpa/src/main/java/com/canoo/dp/impl/platform/data/jpa/SimpleCrudService.java
  platform-extras/dolphin-platform-data-jpa/src/main/java/com/canoo/dp/impl/platform/data/jpa/event/PersistenceListener.java
  platform-extras/dolphin-platform-data-jpa/src/main/java/com/canoo/dp/impl/platform/data/jpa/event/PersistenceListenerManager.java
  platform-extras/dolphin-platform-data/dolphin-platform-data.gradle
  platform-extras/dolphin-platform-data/src/main/java/com/canoo/dp/impl/platform/data/CrudService.java
  platform-extras/dolphin-platform-data/src/main/java/com/canoo/dp/impl/platform/data/EntityWithId.java
  platform-extras/dolphin-platform-data/src/main/java/com/canoo/dp/impl/platform/data/i18n/I18nService.java
  platform-extras/dolphin-platform-data/src/main/java/com/canoo/dp/impl/platform/data/i18n/I18nServiceImpl.java
  platform-extras/dolphin-platform-data/src/main/java/com/canoo/dp/impl/platform/data/i18n/Utf8ResourceBundle.java
  platform-extras/dolphin-platform-data/src/main/java/com/canoo/dp/impl/platform/data/mapping/BeanConverter.java
  platform-extras/dolphin-platform-data/src/main/java/com/canoo/dp/impl/platform/data/mapping/BeanMapper.java
  platform-extras/dolphin-platform-data/src/main/java/com/canoo/dp/impl/platform/data/mapping/BeanMapperImpl.java
  platform-extras/dolphin-platform-data/src/main/java/com/canoo/dp/impl/platform/data/mapping/ConversionException.java
  settings.gradle
Labels: in progress

#832 Docker services: Keycloak
  services/README.md
  services/base/Dockerfile
  services/buildBase.sh
  services/clearDocker.sh
  services/docker-compose.yml
  services/downloadArtifacts.sh
  services/keycloak/Dockerfile
  services/keycloak/ansible/default-client.json
  services/keycloak/ansible/default-realm.json
  services/keycloak/ansible/default-user.json
  services/keycloak/ansible/site.yml
  services/registry/Dockerfile
  services/restart.sh
Labels: in progress

#843 Bugfix for security http connection
  platform-extras/dolphin-platform-security-client/src/main/java/com/canoo/dp/impl/security/KeycloakSecurity.java
Labels: Security, in progress

#844 exception logging
  platform/dolphin-platform-remoting-server/src/main/java/com/canoo/dp/impl/server/context/ClientSessionExecutorImpl.java
Labels: Component: Remoting Server, in progress

#853 Prepare release script
  prepare-release/prepare-release.sh
Labels: Documentation, in progress
